name: DragonRealmsMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.4
description: Plugin for the Dragon Realms server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, _Nobody_]

# plugin.yml is no longer used to define commands.
